server:
  port: 8083
  instance:
    prefer-ip-address: true
spring:
  application:
    name: member
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.20.134/shop?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
