server:
  port: 8084
  instance:
    prefer-ip-address: true
spring:
  application:
    name: message
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.88.128/shop?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: hanwei
    password: hanwei
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.88.128
    port: 6379
logging:
  level:
    org.springframework.security:
      - debug
      - info
    org.springframework.web: error
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
#PRODUCT:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
refreshScopeConfig:
    id: 123456
    name: testAutPushConfig
